"""Add tokens_valid_from_utc to User model

Revision ID: ccc5bbb2d995
Revises: 3e5fea6aaff6
Create Date: 2025-08-07 17:14:49.327359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc5bbb2d995'
down_revision: Union[str, Sequence[str], None] = '3e5fea6aaff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tokens_valid_from_utc', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tokens_valid_from_utc')
    # ### end Alembic commands ###
